### ISSUE TITLE
Backend not forwarding properly after upgrade to 1.14.x/1.15.x

### ISSUE THREAD

**Issue by lord-kyron** [seatsurfing/seatsurfing#222]
Hi,
I started using seatsurfing recently and I deployed version 1.13.8 in Kuberentes with the guide provided in the official documentation.
I've set it up as described Traefik ingressRoute + Nginx reverse proxy before it and it was running great.
However, I decided to upgrade to 1.15.0 latest version - suddenly the backend stopped working giving me this error:
`Get "http://localhost:3000/admin/dashboard": dial tcp [::1]:3000: connect: connection refused`
and respectively this for the UI:
`Get "http://localhost:3001/ui/login": dial tcp [::1]:3001: connect: connection refused`
I tried to deploy a new separate setup with 1.15.0 to start from scratch - it was giving me the same error from the start.
I also tried a new setup from scratch with 1.14.4 - the effect was the same.
So for now only 1.13.8 works for me and I can't understand why.
I am using the documentation as example how to deploy all the version - maybe something changed in 1.14/1.15 which is not properly added to documentation?

I don't know. 
Can someone suggest how can I fix this and run a more recent version?
Thanks!
P.S. - here is my setup (URL are changed on purpose):
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seatsurfing-backend
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seatsurfing-backend
  template:
    metadata:
      labels:
        app: seatsurfing-backend
    spec:
      containers:
      - image: seatsurfing/backend:latest
        name: server
        imagePullPolicy: Always
        ports:
        - name: port-http
          containerPort: 8080
        env:
        - name: POSTGRES_PASS
          valueFrom:
            secretKeyRef:
              name: seatsurfing-db
              key: db-password
        - name: POSTGRES_URL
          value: "postgres://seatsurfing:$(POSTGRES_PASS)@seatsurfing-db/seatsurfing?sslmode=disable"
        - name: JWT_SIGNING_KEY
          value: "a_random_key"
        - name: PUBLIC_URL
          value: "https://book.mycoworking.com" 
        - name: FRONTEND_URL
          value: "https://book.mycoworking.com"
      - image: seatsurfing/booking-ui:latest
        name: booking-ui
        imagePullPolicy: Always
        env:
        - name: FRONTEND_URL
          value: "https://book.mycoworking.com"
      - image: seatsurfing/admin-ui:latest
        name: admin-ui
        imagePullPolicy: Always
        env:
        - name: FRONTEND_URL
          value: "https://book.mycoworking.com"
---
apiVersion: v1
kind: Service
metadata:
  name: seatsurfing-backend
  namespace: services
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: seatsurfing-backend
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: seatsurfing-backend
  namespace: services
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`book.mycoworking.com`)
    kind: Rule
    services:
    - name: seatsurfing-backend
      port: 80
```
