### ISSUE TITLE
TLS certificate error after upgrading to v1.32.1 (OAuth2 login with Microsoft fails)

### ISSUE THREAD

**Issue by dapnii** [seatsurfing/seatsurfing#869]
Hi,

After upgrading the Seatsurfing app from version 1.26.3 to 1.32.1, I encountered a TLS error when attempting to log in using a Microsoft account via OAuth2. Logging in with a local account (seatsurfing.local) still works as expected. After rolling back to old version it also works all as expected.

The error message:

Get "https://name.org/ui/en/login/success/dre6c256-1871-4the-b2av-21505a903op4": tls: failed to verify certificate: x509: certificate signed by unknown authority

It seems like the container is not trusting the certificate chain. Please let me know if possible additional configuration is required or if this is a bug introduced with the new version.

Thanks in advance!

**Comment by virtualzone** [comment]
The contains is not handling TLS at all. Incoming TLS requests must be terminated at a reverse proxy in front of it.
Is name.org your Seatsurfing instance's correct DNS name and is this domain registered under "Settings"?

**Comment by virtualzone** [comment]
The warning icons indicate that your Seatsurfing instance is not accessible via: https://<your-specified-domain-name>/
How do you handle TLS without a reverse proxy?

**Comment by dapnii** [comment]
I’m sorry for misunderstanding regarding the reverse proxy. Yes, I am indeed using an nginx reverse proxy to terminate TLS.

I also tried accessing the web app directly via http://ip_addr:8080, and it loads normally until I click the Microsoft login button, which redirects me to https://name.org/ui/en/login/success/... (the domain name is a placeholder, but it’s correctly set in the app settings). At this point, I get the TLS error:

"tls: failed to verify certificate: x509: certificate signed by unknown authority"

Additionally, when I log in with a local admin account (not using OAuth2) and navigate to the Admin tab in the UI, I get this error:

"dial tcp: lookup (dns_name) on 127.0.0.11:53: server misbehaving"

However, when bypassing the reverse proxy and accessing the app directly via http://ip_addr:8080, the Microsoft OAuth2 login still fails with the same TLS error, but the Admin UI becomes accessible without the DNS lookup error.

**Comment by virtualzone** [comment]
Is your Seatsurfing instance reachable via https scheme on the default port 443?
If not, PR #899 (to be released with version 1.33) will add the ability to specify `PUBLIC_SCHEME` (default https) and `PUBLIC_PORT` (default 443) environment variables.

**Comment by dapnii** [comment]
Yes, the instance itself is reachable via https scheme on the default port 443, but the problem occurs after clicking on "Microsoft" button for Microsoft login. 

I tried new version 1.33.0 today and after clicking on "Microsoft" button for login I get new error:

"Get "https://dns-name.org:3001/ui/en/login/success/...": dial tcp ip_address:3001: connect: connection refused"

Then I realized one more strange thing about logging in with local @seatsurfing.local account. When I log in to https://dns-name/ui with @seatsurfing.local account it works up until the moment I click on "Admin" tab in Booking UI. Then I get below error:

"Get "https://dns-name:3000/admin/en/dashboard": dial tcp: lookup dns-name on 127.0.0.11:53: server misbehaving"

... but when I try to log in to https://dns-name/admin directly with @seatsurfing.local admin account, I am able to log in and navigate through Admin UI.

**Comment by virtualzone** [comment]
Ports 3000 and 3001 should not be accessed directly, but through the server/backend running on port 8080. 
Please share your entire container and proxy configuration, something is wrong there...

**Comment by dapnii** [comment]
docker-compose.yml:
```yaml
services:
  server:
    image: seatsurfing/backend
    restart: always
    networks:
      sql:
      web:
    ports:
      - 8080:8080
    environment:
      POSTGRES_URL: 'postgres://seatsurfing:DB_PASSWORD@db/seatsurfing?sslmode=disable'
      BOOKING_UI_BACKEND: 'booking-ui:3001'
      ADMIN_UI_BACKEND: 'admin-ui:3000'
      PUBLIC_URL: 'https://dns-name.org'
      FRONTEND_URL: 'https://dns-name.org'
      ORG_SIGNUP_MAX_USERS: 999
  booking-ui:
    image: seatsurfing/booking-ui
    restart: always
    networks:
      web:
    environment:
      FRONTEND_URL: 'https://dns-name.org'
  admin-ui:
    image: seatsurfing/admin-ui
    restart: always
    networks:
      web:
    environment:
      FRONTEND_URL: 'https://dns-name.org'
  db:
    image: postgres:16
    restart: always
    networks:
      sql:
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: DB_PASSWORD
      POSTGRES_USER: seatsurfing
      POSTGRES_DB: seatsurfing

volumes:
  db:

networks:
  sql:
  web:
```

/etc/nginx/sites-enabled/seatsurfing:
```nginx 
server {
 listen 443 ssl;
 server_name dns-name.org;
 ssl_certificate /etc/certs/name.cer;
 ssl_certificate_key /etc/certs/name.key;
 ssl_protocols TLSv1.2 TLSv1.3;
 ssl_ciphers HIGH:!aNULL:!MD5;

 location / {
  proxy_pass http://127.0.0.1:8080;
  proxy_set_header Host $host;
  proxy_set_header X-Real-IP $remote_addr;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Proto $scheme;
 }
}

server {
    listen 80;
    server_name dns-name.org;
    return 301 https://$host$request_uri;
}"
```

docker ps -a:

![Image](https://github.com/user-attachments/assets/b695c9eb-265b-4424-aabb-d33856c2f1f2)


Thanks for support, please let me know if anything else is needed.
