### ISSUE TITLE
Issue from upgrading from 1.26.3 to all newer versions

### ISSUE THREAD

**Issue by Vogete** [seatsurfing/seatsurfing#870]
After upgrading from `1.26.3` to any version above (tried every single one but my target is now `1.32.0`), single sign-on (Microsoft) seems to stop working because the page just keeps loading and then times out.

The Administration button on the top bar that directs to `/admin/dashboard` experiences the same behavior. If I directly go to `/admin` and log in with username/password, then `/admin/dashboard` is accessible. Once I navigate back to `/ui` with the `Bookings` button, the Administration button seems to stop working again.

I'm using k8s, and have added `FRONTEND_URL` and `PUBLIC_URL`, as well as `ADMIN_UI_BACKEND` and `BOOKING_UI_BACKEND`. The exact same configuration in 1.26.3 works perfectly.

The same behavior is exhibited in two separate k8s clusters.

**Comment by virtualzone** [comment]
Please see my comment in #869

**Comment by virtualzone** [comment]
PR #871 will improve resilience and logging for auth providers; will be available shortly in version 1.32.2.
Could you please

**Comment by virtualzone** [comment]
Definitely some kind of connectivity issue, probably due to a firewall. The backend can't connect to Microsoft in order to retrieve the user information (I/O Timeout).

**Comment by Vogete** [comment]
Maybe, but that doesn't explain why it works with exactly the same config on 1.26.3

**Comment by Vogete** [comment]
I fixed my firewall issue on my test instance, however, the original issue that I experienced on my production one still exists on both environments. (Now without the timeout error message in the logs, I get a 502 bad gateway during SSO on both instances.)

Furthermore, it seems, that i can't access `https://seatsurfing.example.com/admin/{subpage}` or `https://seatsurfing.example.com/ui/{subpage}` after 1.26.3, because it keeps just loading forever until nginx throws a Bad Gateway error. I can navigate to `https://seatsurfing.example.com/admin` or `https://seatsurfing.example.com`, log in, and click around in the ui or the admin panels, as long as I don't refresh the page. If i roll back to 1.26.3, it all seems to load just fine, no matter how much I refresh, but beyond that, I can only navigate as long as the frontend is doing the page modification, not the browser refresh.

Is there any way to enable some more verbose logging on the server (maybe even debug logging?) so I can see what my deployment is doing? the `DEV` variable doesn't seem to do that much, and `PRINT_CONFIG` also stopped working a while ago, so I can't check what settings Seatsurfing recognizes, only what the pod has set.

**Comment by virtualzone** [comment]
Glad to hear you fixed your firewall issue!

Please try if Seatsurfing works as expected when accessing it directly (without your reverse proxy in between).

**Comment by virtualzone** [comment]
The error means that the server/backend can't connect to the booking ui at port 30000. However:
Are you sure it's port 30,000? This doesn't match your config posted above:

```
- name: ADMIN_UI_BACKEND
  value: "admin-ui:3000"
- name: BOOKING_UI_BACKEND
  value: "booking-ui:3001"
```

**Comment by Vogete** [comment]
I only port forwarded the main `backend` container to port `30000`, and on version `1.26.3` it successfully loaded both the UI and the admin content. And on version `1.33.1` if I accessed `http://localhost:30000/admin`, it shows the login panel, I can use it with a local user, log in and get dropped onto the admin panel. As long as I don't trigger a page refresh, i can navigate in the submenus.

I am using the built-in UI proxy (`DISABLE_UI_PROXY` is set to `0`), so I assume the `ADMIN_UI_BACKEND` and the `BOOKING_UI_BACKEND` variables are supposed to reflect the name of the container which the `backend` container can access these two containers. Or am I misunderstanding that?

**Comment by Vogete** [comment]
I managed to solve it by disabling the UI proxy by doing the following:

1. set `DISABLE_UI_PROXY` to `1`
2. remove `ADMIN_UI_BACKEND` and `BOOKING_UI_BACKEND` because it's not needed
3. Adding ingress paths for both `booking-ui` and `admin-ui` services:

```yaml
# Ingress configuration
spec:
  ingressClassName: nginx-example
  rules:
    - host: seatsurfing.example.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /ui
            pathType: ImplementationSpecific
            backend:
              service:
                name: booking-ui
                port:
                  number: 3001
          - path: /admin
            pathType: ImplementationSpecific
            backend:
              service:
                name: admin-ui
                port:
                  number: 3000
```

So my theory is something changed in the built-in UI proxy that causes this issue. And maybe https://github.com/seatsurfing/seatsurfing/pull/871 too?
